url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Oliver Meyer" # the name of your site, e.g. ACME Corp.
defaults:
  - scope:
      path: "_posts"
    values:
      layout: blog 